print("Disclaimer\n Regarding all of the prompts you will be given, give the prompt then press 'return'")
location = input("Type a location:")
alive = input("Type a living being/creature:")
action = input("Enter a verb:")
building = input("Type in a name of a building:")
noun = input("Enter any type of noun:")
weapon = input("Type a weapon:")
verb = input("Enter another verb:")
date = input("Give a certain date (mm/dd/yy):")
print("The scariest thing happened to me on " + date)
print("I was spending my days off down at " + location + " living at a " + building + ".")
print("Suddenly a giant " + alive + " jumped at me!")
print("At the time I didn't know what it was exactly, but I was scared so I started to " + action + ".")
print("Finally I saw the " + building + " in sight, and I was relieved,")
print("but then another " + alive + " shoved me and I fell into a " + noun + ".")
print("Coincidentally I found a " + weapon + " right behind me,")
print("and I used it to " + verb + " the " + alive + ",")
print("and that was the scariest thing that happened to me on " + date)